name: 推送更新
on:
  schedule:
    - cron: '0 22 * * *'    # 国际标准时间22点（北京时间早上6点发）
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run
        run: python main.py
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "being1943@gmail.com"
          git config --global user.name "being1943"
          git add README.md
          git add docs
          git commit -m "Github Action Auto Updated"
          git push