name: 推送更新
on:
  schedule:
    - cron: '0 22 * * *'    # 国际标准时间22点（北京时间早上6点发）
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: [ '3.7.4' ]
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Build
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "being1943@gmail.com"
          git config --global user.name "being1943"
          git add README.md
          git add docs
          git commit -m "Github Action auto Updated"
          git push